# Generated by Django 5.2.8 on 2025-12-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0003_product_archived_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="zalupa",
            field=models.TextField(blank=True, null=True),
        ),
    ]
