# Generated by Django 5.2.8 on 2025-12-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_order_zalupa'),
        ('shopapp', '0006_order_products'),
    ]

    operations = [
    ]
